# DO NOT EDIT THIS FILE
#
# Please edit /boot/armbianEnv.txt to set supported parameters
#

setenv rootdev "/dev/sda2"
setenv rootfstype "ext4"

test -n "${consoleargs}" || setenv consoleargs "console=ttyAML0,115200n8"
test -n "${loglevel}" || setenv loglevel "1"

test -n "${bootdev}" || setenv bootdev "usb 0"
test -n "${loadaddr}" || setenv loadaddr "0x12000000"

echo "Try to boot from ${bootdev}"
if test -e ${bootdev} /armbianEnv.txt; then
	fatload ${bootdev} ${loadaddr} /armbianEnv.txt
	env import -t ${loadaddr} ${filesize}
fi

# Boot Arguments
setenv bootargs ""
setenv bootargs "${bootargs} root=${rootdev} rootwait rw rootfstype=${rootfstype}"
setenv bootargs "${bootargs} ${consoleargs} no_console_suspend consoleblank=0"
setenv bootargs "${bootargs} loglevel=${loglevel}"

# Booting
fatload ${bootdev} 0x20800000 /uImage
fatload ${bootdev} 0x22000000 /uInitrd
fatload ${bootdev} 0x21800000 /dtb/meson8b-onecloud.dtb

fdt addr 21800000

if test "${vpu}" = "0"; then fdt rm /mesonstream; fdt rm /vdec; fdt rm /ppmgr; fi
if test "${hdmioutput}" = "0"; then fdt rm /mesonfb; fi

bootm 0x20800000 0x22000000 0x21800000

# Recompile with:
# mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr
